var Promise = require('promise');
var fs = require('fs');

module.exports = {
  access: Promise.denodeify(fs.access),
  appendFile: Promise.denodeify(fs.appendFile),
  chmod: Promise.denodeify(fs.chmod),
  chown: Promise.denodeify(fs.chown),
  close: Promise.denodeify(fs.close),
  exists: Promise.denodeify(fs.exists),
  fchmod: Promise.denodeify(fs.fchmod),
  fchown: Promise.denodeify(fs.fchown),
  fstat: Promise.denodeify(fs.fstat),
  ftruncate: Promise.denodeify(fs.ftruncate),
  futimes: Promise.denodeify(fs.futimes),
  lchmod: Promise.denodeify(fs.lchmod),
  lchown: Promise.denodeify(fs.lchown),
  link: Promise.denodeify(fs.link),
  lstat: Promise.denodeify(fs.lstat),
  mkdir: Promise.denodeify(fs.mkdir),
  open: Promise.denodeify(fs.open),
  read: Promise.denodeify(fs.read),
  readdir: Promise.denodeify(fs.readdir),
  readFile: Promise.denodeify(fs.readFile),
  readlink: Promise.denodeify(fs.readlink),
  realpath: Promise.denodeify(fs.realpath),
  rename: Promise.denodeify(fs.rename),
  rmdir: Promise.denodeify(fs.rmdir),
  stat: Promise.denodeify(fs.stat),
  symlink: Promise.denodeify(fs.symlink),
  truncate: Promise.denodeify(fs.truncate),
  unlink: Promise.denodeify(fs.unlink),
  utimes: Promise.denodeify(fs.utimes),
  write: Promise.denodeify(fs.write),
  writeFile: Promise.denodeify(fs.writeFile)
};
